Added Detector Library Samples
aws-samples/amazon-codeguru-detectors pull request #17
Opened 2024-05-03 12:55 UTC by aastjais

*Added Detector Library Samples:*

Added Samples tests for Java, Python, CSharp, Ruby, GoLang, JavaScript, TypeScript, Cloudformation and Terraform.

2024-05-06 16:10 UTC, yanjunw-amazon requested changes
Please do not include `csharp/.DS_Store`

2024-05-06 18:44 UTC, grl-wang commented on cloudformation/src/detectors/disabled-glue-cat-encrypt-cloudformation/non-compliant.yaml
> +          # Compliant: Glue Data Catalog Encryption is disabled.
is this a compliant or non compliant example?

2024-05-06 18:44 UTC, grl-wang commented on golang/src/detectors/http-trace-file-server-as-handler/HTTPTraceFileServerAsHandler.go
> +	//Noncompliant: `http.FileServer` used
pls correct the format of the noncompliant comment

```
// Noncompliant: `http.FileServer` used
````

2024-05-06 18:44 UTC, grl-wang commented on golang/src/detectors/http-trace-file-server-as-handler/HTTPTraceFileServerAsHandler.go
> +	//Compliant: `http.FileServer` not used
fix the comment format

2024-05-06 18:44 UTC, grl-wang commented on golang/src/detectors/weak-random-number-generation/WeakRandomNumberGeneration.go
> +		// Noncompliant: `math.rand` is used for generating random number.
any compliant example for this rule?

2024-05-07 04:43 UTC, aastjais commented on cloudformation/src/detectors/disabled-glue-cat-encrypt-cloudformation/non-compliant.yaml
> +          # Compliant: Glue Data Catalog Encryption is disabled.
comment mistake, will correct this

2024-05-07 16:47 UTC, grl-wang approved these changes

2024-05-07 16:47 UTC, merged