Add compliant and noncompliant samples for jsx rules
aws-samples/amazon-codeguru-detectors pull request #28
Opened 2024-06-19 14:31 UTC by ankit-amazon

Add JSX detector library samples.

2024-06-19 18:44 UTC, karmakri commented on jsx/src/detectors/disallow-bind/DisallowBindCompliant.jsx
> +const Compliant = ({ onClick }) => {
can you please change it to `compliant` ?

2024-06-19 18:44 UTC, karmakri commented on jsx/src/detectors/jsx-label-not-i18n/JsxLabelNotI18nCompliant.jsx
> +const Compliant = () => {
can you please change it to `compliant` ?

2024-06-19 18:46 UTC, karmakri commented on jsx/src/detectors/jsx-label-not-i18n/JsxLabelNotI18nCompliant.jsx
> +    // {fact rule=jsx-label-not-i18n@v1.0 defects=0}
Can you please add this fact label before line no. 8 ?

2024-06-19 18:46 UTC, karmakri commented on jsx/src/detectors/jsx-label-not-i18n/JsxLabelNotI18nNoncompliant.jsx
> +    // {fact rule=jsx-label-not-i18n@v1.0 defects=1}
Can you please add this fact label before line no. 8 ?

2024-06-20 13:56 UTC, pratik-amazon approved these changes

2024-06-20 14:35 UTC, berkcirisci approved these changes

2024-06-26 17:34 UTC, pattersonz commented on jsx/src/detectors/disallow-bind/DisallowBindCompliant.jsx
This rule is too much. This will ruffle feathers if released, and should not be.

2024-06-26 17:36 UTC, pattersonz commented on jsx/src/detectors/jsx-label-not-i18n/JsxLabelNotI18nCompliant.jsx
This should not be released.

2024-06-26 17:37 UTC, pattersonz requested changes
DisallowBind and LabelNotCompliant should not be released.

2024-06-28 17:31 UTC, pattersonz approved these changes

2024-07-02 06:47 UTC, merged